# Generated by Django 3.2.3 on 2021-05-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressInfo',
            fields=[
                ('express_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
                ('note', models.TextField()),
                ('locate', models.CharField(max_length=15)),
            ],
        ),
    ]
