# Generated by Django 3.2.3 on 2021-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressInfo',
            fields=[
                ('express_id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='快递ID')),
                ('building', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12')], max_length=5, verbose_name='楼宇号')),
                ('receiver', models.CharField(max_length=10, verbose_name='收件人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('locate', models.CharField(blank=True, max_length=15, null=True, verbose_name='位置号')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='签收时间')),
            ],
            options={
                'verbose_name': '快递信息',
                'verbose_name_plural': '快递信息',
            },
        ),
        migrations.CreateModel(
            name='MainWareHouseAdmin',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(max_length=12, verbose_name='手机')),
                ('employee_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='员工id')),
            ],
            options={
                'verbose_name': '总仓管理员',
                'verbose_name_plural': '总仓管理员',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(max_length=12, verbose_name='手机')),
                ('receive_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='收件人id')),
                ('self_service', models.BooleanField(verbose_name='自助取件')),
                ('building', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12')], max_length=5, verbose_name='收件地址')),
            ],
            options={
                'verbose_name': '收件人',
                'verbose_name_plural': '收件人',
            },
        ),
        migrations.CreateModel(
            name='WareHouseWorker',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(max_length=12, verbose_name='手机')),
                ('employee_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='员工id')),
                ('level', models.CharField(choices=[('0', '分仓管理员'), ('1', '分仓工作人员')], max_length=2, verbose_name='职工类别')),
                ('building', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12')], max_length=5, verbose_name='负责的楼宇')),
            ],
            options={
                'verbose_name': '分仓人员',
                'verbose_name_plural': '分仓人员',
            },
        ),
    ]
