# Generated by Django 3.2.3 on 2021-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressinfo',
            name='receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='签收时间'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='building',
            field=models.CharField(max_length=50, verbose_name='楼宇号'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='express_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='快递ID'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='locate',
            field=models.CharField(max_length=15, verbose_name='位置号'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='note',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='receiver',
            field=models.CharField(max_length=10, verbose_name='收件人'),
        ),
    ]
