# Generated by Django 3.2.3 on 2021-06-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwarehouseadmin',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='warehouseworker',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='性别'),
        ),
    ]
