# Generated by Django 3.2.3 on 2021-06-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210601_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expressinfo',
            options={'verbose_name': '快递信息', 'verbose_name_plural': '快递信息'},
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='express_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='快递ID'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='locate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='位置号'),
        ),
        migrations.AlterField(
            model_name='expressinfo',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
